### ISSUE TITLE
TypeError: `req.next` is not a function

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#195]
Many people are getting this error while using the login feature on their local system, those have good experience in working with JWT can work on this.
Relevant links have been added to help solve the issue.

### **Error report**
```
Server started on port 3000
(node:14720) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:14720) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: req.next is not a function
    at done (C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\express\lib\response.js:1003:25)
    at tryRender (C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\express\lib\application.js:642:5)
    at Function.render (C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\express\lib\response.js:1008:7)
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\app.js:153:15
    at Array.forEach (<anonymous>)
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\app.js:144:13
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\model.js:4850:16
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\model.js:4850:16
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\model.js:4873:21
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\query.js:4397:11
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\kareem\index.js:136:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Emitted 'error' event on Function instance at:
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\model.js:4852:13
    at C:\Users\User\Desktop\New folder (2)\new\BlogSite\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### **To Reproduce**
1. Log In
2. Comment on any post

### **Expected behavior**
Should add a comment on the post

### Relevant links to help resolve the issue-
https://github.com/expressjs/express/issues/4093
https://stackoverflow.com/questions/60943856/typeerror-req-next-is-not-a-function-node-js-express-error
https://stackoverflow.com/questions/46203475/typeerror-req-next-is-not-a-function/46204169

**Comment by prajjwalarora** [comment]
@Pranav016 I wanna work on this issue.

**Comment by vieee** [comment]
Hello @Pranav016, I would like to work on this issue, could I work on it ?

**Comment by Pranav016** [comment]
> I tried following the steps to produce the error but it works fine. No error came up like this in my case.

Try a few times, sign up or log in, comment, create posts. If it still doesn't give any error then I'll close this issue..

**Comment by aniketlodh** [comment]
https://user-images.githubusercontent.com/55927827/110744174-440ae200-825f-11eb-9dcf-629d1e27e5bb.mp4

I have tried several times but the error is not showing up. You can refer to the video I have attached.

**Comment by Pranav016** [comment]
>  vid.mp4 
> I have tried several times but the error is not showing up. You can refer to the video I have attached.

This issue wasn't disrupting the website, it was on the console. Maybe it is only on my system. Closing this issue for now, will reopen if required.
